### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by builtbybasit** [agituts/gemini-2-tts#1]
I followed the provided steps but It doesn't work anymore. The code is running without any Errors. Can you please check?

Maybe they changed something in their API Can you please update the code?

**Comment by builtbybasit** [comment]
.env file
```env
...
VOICE_A=Puck    # Optional: Default is Puck. Current options are Puck, Charon, Kore, Fenrir, and Aoede.
VOICE_B=Kore    # Optional: Default is Kore. Current options are Puck, Charon, Kore, Fenrir, and Aoede.
...
```

I forgot to remove the comment. Now, it's working fine.

Changed .env file
```env
...
VOICE_A=Puck
VOICE_B=Kore
...
```

**Comment by agituts** [comment]
> .env file
> 
> ```dotenv
> ...
> VOICE_A=Puck    # Optional: Default is Puck. Current options are Puck, Charon, Kore, Fenrir, and Aoede.
> VOICE_B=Kore    # Optional: Default is Kore. Current options are Puck, Charon, Kore, Fenrir, and Aoede.
> ...
> ```
> 
> I forgot to remove the comment. Now, it's working fine.
> 
> Changed .env file
> 
> ```dotenv
> ...
> VOICE_A=Puck
> VOICE_B=Kore
> ...
> ```

Okay, glad it worked!
